# Generated by Django 2.2 on 2020-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200424_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
