# Generated by Django 2.2 on 2020-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_trusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trusted',
        ),
    ]
