# Generated by Django 2.2 on 2020-12-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20201211_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinfactoryrequest',
            name='status',
            field=models.CharField(choices=[('r', 'reject'), ('a', 'accepted'), ('p', 'pending')], max_length=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='complete_name',
            field=models.CharField(error_messages={'unique': 'این نام سازمان تکراری میباشد'}, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(error_messages={'unique': 'این نام سازمان تکراری میباشد'}, max_length=100, unique=True),
        ),
    ]
