# Generated by Django 2.2 on 2020-05-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20200511_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
