# Generated by Django 2.2 on 2020-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20200512_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factory',
            unique_together={('organization', 'title')},
        ),
    ]
