# Generated by Django 2.2 on 2020-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20200513_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factory',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
