# Generated by Django 2.2 on 2020-05-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_position_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
