# Generated by Django 2.2 on 2020-05-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20200527_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('factory', 'title')},
        ),
    ]
