# Generated by Django 2.2 on 2020-06-02 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20200602_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
