# Generated by Django 2.2 on 2020-06-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20200602_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='user',
            new_name='admin_user',
        ),
    ]
