# Generated by Django 2.2 on 2020-06-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_auto_20200602_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_user', to='organizations.AdminGroup'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
