# Generated by Django 2.2 on 2020-06-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20200602_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='admin_user',
            new_name='user',
        ),
    ]
