# Generated by Django 2.2 on 2020-06-02 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0030_auto_20200602_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminuser',
            unique_together={('user', 'admin_group')},
        ),
    ]
