# Generated by Django 2.2 on 2020-06-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20200602_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='opposite_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposite_type', to='organizations.RelationType'),
        ),
    ]
