# Generated by Django 2.2 on 2020-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_relation_opposite_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='opposite_type',
        ),
    ]
