# Generated by Django 2.2 on 2020-06-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_remove_relation_opposite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='opposite_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.RelationType'),
        ),
    ]
