# Generated by Django 2.2 on 2020-06-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_relationtype_opposite_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Status'),
        ),
    ]
