# Generated by Django 2.2 on 2020-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_auto_20200814_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
