# Generated by Django 2.2 on 2020-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0038_auto_20200815_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='rel_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
