# Generated by Django 2.2 on 2020-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_auto_20200815_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthority',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
