# Generated by Django 3.0.2 on 2020-02-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200201_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_faq',
            field=models.BooleanField(default=False),
        ),
    ]
