# Generated by Django 2.2 on 2020-05-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
