# Generated by Django 2.2 on 2020-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200526_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conformity',
            old_name='risk',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='publisher',
        ),
        migrations.AddField(
            model_name='conformity',
            name='is_conformity',
            field=models.BooleanField(default=False),
        ),
    ]
