# Generated by Django 2.2 on 2020-05-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200528_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='action',
            name='publisher',
        ),
    ]
