# Generated by Django 2.2 on 2020-05-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200528_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformitygallery',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conformitygallery', to='reports.Conformity'),
        ),
    ]
