# Generated by Django 2.2 on 2020-05-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200531_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='executiv_status',
        ),
        migrations.RemoveField(
            model_name='action',
            name='followe_status',
        ),
        migrations.RemoveField(
            model_name='action',
            name='follower_department',
        ),
        migrations.RemoveField(
            model_name='action',
            name='follower_owner',
        ),
        migrations.AlterField(
            model_name='action',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='reports.Conformity'),
        ),
    ]
