# Generated by Django 2.2 on 2020-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200531_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
