# Generated by Django 2.2 on 2020-05-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_action_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_status', to='reports.ActionStatus'),
        ),
        migrations.AlterField(
            model_name='action',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='reports.Conformity'),
        ),
        migrations.AlterField(
            model_name='actiongallery',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_gallery', to='reports.Action'),
        ),
    ]
