# Generated by Django 2.2 on 2020-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200531_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
