# Generated by Django 2.2 on 2020-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_conformity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
