# Generated by Django 2.2 on 2020-06-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_action_is_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_confirm',
        ),
    ]
