# Generated by Django 2.2 on 2020-08-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_auto_20200815_2202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0013_remove_action_is_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='action',
            name='owner_factory',
        ),
        migrations.RemoveField(
            model_name='action',
            name='text',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='owner_factory',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='part',
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='receiver_factory',
        ),
        migrations.AddField(
            model_name='conformity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conformity',
            name='receiver_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Department'),
        ),
        migrations.AlterField(
            model_name='action',
            name='execute_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_dep', to='organizations.Department'),
        ),
        migrations.AlterField(
            model_name='action',
            name='execute_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive_status', to='reports.ActionStatus'),
        ),
        migrations.AlterField(
            model_name='conformity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conformity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Status'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_owner_factory', to='organizations.Factory')),
                ('receiver_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Factory')),
            ],
        ),
        migrations.AddField(
            model_name='conformity',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Inspection'),
        ),
    ]
