# Generated by Django 2.2 on 2020-08-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_action_execute_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='conformity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='reports.Conformity'),
        ),
    ]
