# Generated by Django 2.2 on 2020-08-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200817_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='reports.Conformity'),
        ),
    ]
