# Generated by Django 2.2 on 2020-08-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20200821_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformity',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conformity', to='reports.Inspection'),
        ),
    ]
