# Generated by Django 2.2 on 2020-08-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_auto_20200815_2202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('percent', models.FloatField()),
                ('price_with_tax', models.DecimalField(decimal_places=0, max_digits=15)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Factory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
