# Generated by Django 2.2 on 2020-08-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_factoryplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryplan',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
