# Generated by Django 2.2 on 2020-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_factoryplan_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryplan',
            name='increase_count',
            field=models.IntegerField(default=0),
        ),
    ]
