# Generated by Django 2.2 on 2020-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_factoryplan_increase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryplan',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
